module Jfy
  module Codes
    CTL_REGISTER = 0x30
    CTL_READ     = 0x31
    CTL_WRITE    = 0x32
    CTL_EXECUTE  = 0x33

    # Register
    OFFLINE_QUERY = [CTL_REGISTER, 0x40]
    SEND_ADDRESS  = [CTL_REGISTER, 0x41]
    RE_REGISTER   = [CTL_REGISTER, 0x44]

    # Register Response
    REGISTER_REQUEST = [CTL_REGISTER, 0xBF]
    ADDRESS_CONFIRM  = [CTL_REGISTER, 0xBE]

    # Read
    READ_DESCRIPTION    = [CTL_READ, 0x40]
    READ_RW_DESCRIPTION = [CTL_READ, 0x41]
    QUERY_NORMAL_INFO   = [CTL_READ, 0x42]
    QUERY_INVERTER_INFO = [CTL_READ, 0x43]
    QUERY_SET_INFO      = [CTL_READ, 0x44]
    QUERY_TIME          = [CTL_READ, 0x45]

    # Read
    READ_DESCRIPTION_RESP    = [CTL_READ, 0xBF]
    READ_RW_DESCRIPTION_RESP = [CTL_READ, 0xBE]
    QUERY_NORMAL_INFO_RESP   = [CTL_READ, 0xBD]
    QUERY_INVERTER_INFO_RESP = [CTL_READ, 0xBC]
    QUERY_SET_INFO_RESP      = [CTL_READ, 0xBB]
    QUERY_TIME_RESP          = [CTL_READ, 0xBA]
  end
end
